# Configuration existante conservée.
# Ajouter uniquement :
plugins:
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-responsive-image
  - jekyll-sitemap

responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 480
    - width: 768
    - width: 1200
